FROM bitnami/php-fpm:7.4.33-debian-11-r25

USER root

RUN install_packages \
    imagemagick \
    php7.4-cli \
    php7.4-json \
    php7.4-curl \
    php7.4-gd \
    php7.4-ldap \
    php7.4-mbstring \
    php7.4-mysql \
    php7.4-soap \
    php7.4-sqlite3 \
    php7.4-xml \
    php7.4-zip \
    php7.4-intl \
    php7.4-common \
    php7.4-dev \
    php7.4-opcache \
    php-redis \
    openssl \
    nano \
    graphicsmagick \
    ghostscript \
    default-mysql-client \
    iputils-ping \
    locales \
    sqlite3
    

# Update PHP configuration
RUN sed -i -e 's/^error_reporting\s*=.*/error_reporting = E_ALL/' /opt/bitnami/php/etc/php.ini && \
    sed -i -e 's/^display_errors\s*=.*/display_errors = On/' /opt/bitnami/php/etc/php.ini && \
    sed -i -e 's/^zlib.output_compression\s*=.*/zlib.output_compression = Off/' /opt/bitnami/php/etc/php.ini && \
    sed -i -e 's/^post_max_size\s*=.*/post_max_size = 32M/' /opt/bitnami/php/etc/php.ini && \
    sed -i -e 's/^upload_max_filesize\s*=.*/upload_max_filesize = 32M/' /opt/bitnami/php/etc/php.ini
