services:
  brt_ss_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8087:80
      - 8088:8088
      - 8089:8089
    environment:
      - NODE_ENV=production
    sysctls:
      net.ipv4.ip_unprivileged_port_start: '0'
    volumes:
      # Mount the project root
      # - /var/www/html/brighton:/var/www/html
      - /c/xampp/htdocs/brighton-project:/var/www/html
      # Mount the environment file individually into the same container path
      # - /var/www/html/_ss_environment.php:/var/www/html/_ss_environment.php:ro
      - /c/xampp/htdocs/_ss_environment.php:/var/www/html/_ss_environment.php:ro
      # Other volumes
      # - /var/log/nginx:/var/log/nginx
      - /c/xampp/htdocs/brighton-project/config/nginx:/etc/nginx/sites-available
    depends_on:
      - php_fpm7
    networks:
      - mynetwork

  php_fpm7:   
    build:
      context: .
      dockerfile: php-fpm/Dockerfile
    volumes:
      # Mount the project root
      # - /var/www/html/brighton:/var/www/html
      - /c/xampp/htdocs/brighton-project:/var/www/html
      # Mount the environment file individually
      # - /var/www/html/_ss_environment.php:/var/www/html/_ss_environment.php:ro
      - /c/xampp/htdocs/_ss_environment.php:/var/www/html/_ss_environment.php:ro
    networks:
      - mynetwork

  php_xhgui:
    build:
      context: .
      dockerfile: php-xhgui/Dockerfile
    networks:
      - mynetwork

  nginx_xhgui:
    build:
      context: .
      dockerfile: nginx-xhgui/Dockerfile
    ports:
      - 8081:80
    depends_on:
      - php_xhgui
    networks:
      - mynetwork
  
  mongo:
    image: mongo:4.4.1
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

